### ISSUE TITLE
404 for index.html

### ISSUE THREAD

**Issue by Rakeshv87** [osrf/rvizweb#16]
Followed readme. couldnt launch the landing page with URL:
http://localhost:8001/rvizweb/www/index.html

2019-01-28 19:36:00,964 - roswww - INFO - roswww : # of packages : 349
2019-01-28 19:36:00,964 - roswww - INFO - roswww : Weg Page root : /
registered capabilities (classes):
 - rosbridge_library.capabilities.call_service.CallService
 - rosbridge_library.capabilities.advertise.Advertise
 - rosbridge_library.capabilities.publish.Publish
 - rosbridge_library.capabilities.subscribe.Subscribe
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - rosbridge_library.capabilities.advertise_service.AdvertiseService
 - rosbridge_library.capabilities.service_response.ServiceResponse
 - rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
2019-01-28 19:36:01,008 - roswww - INFO - roswww : Initialised
2019-01-28 19:36:01,008 - roswww - INFO - roswww : Attempting to start webserver on port 8001
2019-01-28 19:36:01,009 - roswww - INFO - roswww : Webserver successfully started on port 8001
[INFO] [1548732961.259776]: Rosbridge WebSocket server started on port 9090
WARNING:tornado.access:404 GET /rvizweb/www/index.html (::1) 1.61ms
WARNING:tornado.access:404 GET /rvizweb/www/index.html (::1) 2.42ms
WARNING:tornado.access:404 GET /rvizweb/www/index.html (::1) 2.14ms

**Comment by chapulina** [comment]
1. Are you sure you're serving on `localhost`? The host would be different if you're in a docker container for example.
1. Do you see a list of packages when you go to http://localhost:8001 ? Is `rvizweb` listed there?

**Comment by knorth55** [comment]
I have the same problem.
I got packages listed on `http://localhost:8001` and i can access `http://localhost:8001/rvizweb`.
When I directory open `ws/install/share/rvizweb/www/index.html`, I can open the RVizweb GUI.

**Comment by knorth55** [comment]
i found out that this error caused by `roswww` version.
I need to use `0.1.11` and above to prevent this problem.
I made a release request for kinetic devel https://github.com/tork-a/roswww/issues/48.

**Comment by knorth55** [comment]
https://github.com/ros/rosdistro/pull/20785
now `roswww` `0.1.12` is released in kinetic.

**Comment by chapulina** [comment]
Thanks, @knorth55 ! @Rakeshv87 , has your problem been solved?

**Comment by knorth55** [comment]
@chapulina my problem is solved with `roswww` `0.1.12`

**Comment by weiqiyang** [comment]
I have the same problem.
The latest version for `roswww` on `indigo` is `0.1.10`, so I changed to ubuntu16.04 with `roswww 0.1.12`.
Now I can open the GUI from the path start with `file:///`.
But from [localhost:8001/rvizweb/www/index.html](http://localhost:8001/rvizweb/www/index.html), I still get `404: Not Found`.

**Comment by knorth55** [comment]
@weiqiyang can you access to `locahost:8001`?
if not, maybe you forgot to build it with installation.
```
mkdir ~/rvizweb/src -b
cd ~/rvizweb
catkin config --install
cd ~/rvizweb/src
wstool set osrf/rvizweb --git https://github.com/osrf/rvizweb.git
wstool update
catkin build
source ~/rvizweb/install/setup.bash
roslaunch rvizweb rvizweb.launch
```

**Comment by Kad91** [comment]
I have the latest version of roswww ( 0.1.12 ), I can access to `locahost:8001` and can see the Package List and `rvizweb` is in. However, with localhost:8001/rvizweb/www/index.html, I still get 404: Not Found.

**Comment by chapulina** [comment]
@Kad91 , did you get any errors while building? Can you paste your build logs somewhere for us to take a look?

**Comment by Kad91** [comment]
I get this after trying `. ~/.bashrc` 

```. ~/.bashrc
/home/info/.bashrc:16: command not found: shopt
/home/info/.bashrc:24: command not found: shopt
/home/info/.bashrc:111: command not found: shopt
/usr/share/bash-completion/bash_completion:45: command not found: shopt
/usr/share/bash-completion/bash_completion:1461: parse error near `|'
\[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ ```

**Comment by jubeira** [comment]
@Kad91 you could also try out the install instructions in [this branch](https://github.com/osrf/rvizweb/pull/32/files), which don't have that step that is failing.

**Comment by Kad91** [comment]
I get that after doing `curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -` 

```
## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://fr.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu bionic-updates InRelease 
Hit:3 http://ppa.launchpad.net/mosquitto-dev/mosquitto-ppa/ubuntu bionic InRelease
Hit:4 http://deb.playonlinux.com trusty InRelease                  
Hit:5 http://security.ubuntu.com/ubuntu bionic-security InRelease  
Ign:6 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  InRelease
Hit:7 http://download.opensuse.org/repositories/home:/strycore/xUbuntu_16.04  Release
Hit:8 https://deb.nodesource.com/node_10.x bionic InRelease        
Hit:9 https://packages.microsoft.com/repos/vscode stable InRelease 
Hit:10 http://fr.archive.ubuntu.com/ubuntu bionic-backports InRelease
Hit:11 http://packages.ros.org/ros/ubuntu bionic InRelease         
Ign:12 https://download.docker.com/linux/debian bionic InRelease   
Hit:13 https://download.docker.com/linux/ubuntu bionic InRelease
Err:14 https://download.docker.com/linux/debian bionic Release
  404  Not Found [IP: 143.204.229.32 443]
Reading package lists... Done                      
E: The repository 'https://download.docker.com/linux/debian bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Error executing command, exiting


```

**Comment by Kad91** [comment]
I had an issue with `apt-get update` which looks solved now. I modified the files and followed the new instructions. I am connected on port 8001 but still get `404: Not Found`

**Comment by GavinStrunk** [comment]
Are you using catkin_make install and not catkin tools like catkin build? I had this problem when I tried it that way. It doesn't install the index.html or install the bower dependencies so even when you get past the 404 error I got a blank page. Once I switched to doing what the instructions actually said :) it worked on Ubuntu 18 and ros melodic with roswww 0.1.12.

**Comment by Kad91** [comment]
Yes, I used catkin_make install as mentioned in the instructions. Like the issue #35 , connected on port 8001, I get a blank page with `http://localhost:8001/rvizweb/` and 404 error with `http://localhost:8001/rvizweb/www/index.html`.

**Comment by helenol** [comment]
+1, having the same issue on 18.04 melodic. Also built with catkin build first, then catkin_make, no difference. roswww version 0.1.12. Get a list of packages in the root of the webserver (including rvizweb), 404 on the web interface.

Launch output:
```
SUMMARY
========

PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /rvizweb/global_config: <...>

NODES
  /
    interactive_marker_proxy (interactive_marker_proxy/proxy)
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)
    roswww (roswww/webserver.py)
    tf2_web_republisher (tf2_web_republisher/tf2_web_republisher)

ROS_MASTER_URI=http://localhost:11311

process[rosbridge_websocket-1]: started with pid [12873]
process[rosapi-2]: started with pid [12874]
process[roswww-3]: started with pid [12875]
process[tf2_web_republisher-4]: started with pid [12876]
process[interactive_marker_proxy-5]: started with pid [12877]
registered capabilities (classes):
 - rosbridge_library.capabilities.call_service.CallService
 - rosbridge_library.capabilities.advertise.Advertise
 - rosbridge_library.capabilities.publish.Publish
 - rosbridge_library.capabilities.subscribe.Subscribe
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - rosbridge_library.capabilities.advertise_service.AdvertiseService
 - rosbridge_library.capabilities.service_response.ServiceResponse
 - rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
2019-09-27 09:52:25,754 - roswww - INFO - roswww : # of packages : 201
2019-09-27 09:52:25,754 - roswww - INFO - roswww : Weg Page root : /
[INFO] [1569570745.780404]: Rosbridge WebSocket server started on port 9090
2019-09-27 09:52:25,803 - roswww - INFO - roswww : Initialised
2019-09-27 09:52:25,803 - roswww - INFO - roswww : Attempting to start webserver on port 8001
2019-09-27 09:52:25,803 - roswww - INFO - roswww : Webserver successfully started on port 8001
```

**Comment by corey-mitchell** [comment]
I am also having this issue. I followed the "Quick start", the only difference being that I used catkin build rather than catkin_make. 

OS:
Ubuntu 16.04 LTS

ROS Version:
Kinetic

roswww version:
0.1.2

When starting using 'roslaunch rvizweb rvizweb.launch' my output is as follows:

```
PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rvizweb/global_config: <...>

NODES
  /
    interactive_marker_proxy (interactive_marker_proxy/proxy)
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)
    roswww (roswww/webserver.py)
    tf2_web_republisher (tf2_web_republisher/tf2_web_republisher)

ROS_MASTER_URI=http://localhost:11311

process[rosbridge_websocket-1]: started with pid [23246]
process[rosapi-2]: started with pid [23247]
process[roswww-3]: started with pid [23248]
process[tf2_web_republisher-4]: started with pid [23249]
process[interactive_marker_proxy-5]: started with pid [23250]
registered capabilities (classes):
 - rosbridge_library.capabilities.call_service.CallService
 - rosbridge_library.capabilities.advertise.Advertise
 - rosbridge_library.capabilities.publish.Publish
 - rosbridge_library.capabilities.subscribe.Subscribe
 - <class 'rosbridge_library.capabilities.defragmentation.Defragment'>
 - rosbridge_library.capabilities.advertise_service.AdvertiseService
 - rosbridge_library.capabilities.service_response.ServiceResponse
 - rosbridge_library.capabilities.unadvertise_service.UnadvertiseService
2019-10-10 09:39:59,975 - roswww - INFO - roswww : # of packages : 380
2019-10-10 09:39:59,975 - roswww - INFO - roswww : Weg Page root : /
2019-10-10 09:40:00,111 - roswww - INFO - roswww : Initialised
2019-10-10 09:40:00,111 - roswww - INFO - roswww : Attempting to start webserver on port 8001
2019-10-10 09:40:00,114 - roswww - INFO - roswww : Webserver successfully started on port 8001
[INFO] [1570718406.430196, 27.991200]: Rosbridge WebSocket server started on port 9090
```

When I navigate to http://localhost:8001/rvizweb/www/index.html I receive the 404 error. So I tried localhost:8001 to see if rvizweb was in the package list, which it is. I then made my way to localhost:8001/rvizweb but received a blank page (screenshot below).

![rvizwebError](https://user-images.githubusercontent.com/37916145/66580135-84829f80-eb43-11e9-90e1-243e2d7c1e37.png)

Any help would be much appreciated. Thanks in advance.

**Comment by VinayMaida** [comment]
so is it solved?

**Comment by naointingagain** [comment]
I am getting the 404 error when I open index.html as well. I am also getting these errors when running `roslaunch rvizweb rvizweb.launch` :
`ERROR: cannot launch node of type [rosbridge_server/rosbridge_websocket]: Cannot locate node of type [rosbridge_websocket] in package [rosbridge_server]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [rosapi/rosapi_node]: Cannot locate node of type [rosapi_node] in package [rosapi]. Make sure file exists in package path and permission is set to executable (chmod +x)
ERROR: cannot launch node of type [tf2_web_republisher/tf2_web_republisher]: Cannot locate node of type [tf2_web_republisher] in package [tf2_web_republisher]. Make sure file exists in package path and permission is set to executable (chmod +x)
` however, I can run these 3 nodes seperately using their individual commands.
At the end it says : `roswww - INFO - roswww : Webserver successfully started on port 8001
`

**Comment by mfahadrobotics** [comment]
I am facing the same issue. There is no error but I am getting the 404 error. Anyone got to solve it? I already tried the things suggested above.

**Comment by Owen-Liuyuxuan** [comment]
In Ubuntu 18.04 melodic, I manage to solve the problem.

In the workspace directory after running "catkin_make install", I at the first time run 
```
source devel/setup.bash
```
Then I see 404. (ROS package list correct but 404 in index.html)

Then I run 
```
source install/setup.bash 
```
instead. And this time, I manage to get everything running.

**Comment by wumingpu** [comment]
first delete the files in the path `"~/ws/install/shared/rvizweb/www/*"`
`rm -rf ~/ws/install/shared/rvizweb/www/*`
then copy the files in the path `"~/ws/build/rvizweb/www/*"` to the path `"~/ws/install/shared/rvizweb/www/*"`
`cp -r ~/ws/build/rvizweb/www/* ~/ws/install/share/rvizweb/www/`

the url http://localhost:8001/rvizweb/www/index.html can open now.

**Comment by Felix-Tr** [comment]
Thanks! @wumingpu, this worked for me I can now see the UI
